config/routes.rb
Rails.application.routes.draw do
  resources :users ,:only=>[:edit,:new,:create,:update] do 
   collection do
   get :login
   post :authorize
   get :logout
   end
  end
  resources :event_sessions
  resources :main ,:only=>[:index] do
    collection do
      post :login
      get :logout
    end
  end
  resources :questions ,:only=>[:index,:create] do
    member do
      get :vote_up
      post :remove
    end
    collection do
      get :refresh_questions
    end
  end

   root 'main#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :email,:encrypted_password
	validates_uniqueness_of :email
	validates_length_of :password, :minimum => 6,:allow_blank=>true
  before_save :encrypt_password
	after_save :clear_password
    attr_accessor :password 
    private 
    def encrypt_password
  	  self.encrypted_password=Digest::SHA1.hexdigest(self.password) if self.password.present?
    end

    def clear_password
       self.password=nil
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login ,:except=>[:login,:authorize]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

def login
end

def authorize
  user=User.find_by_email params[:email]
  if user && user.encrypted_password==Digest::SHA1.hexdigest(params[:password])
      session[:current_user]=user 
      redirect_to params[:redirect_url] || '/' and return
  end
  flash[:error]="We could not authorize user with provided email and password"
  redirect_to login_users_path and return
end

def logout
  session[:current_user]=nil
  redirect_to login_users_path
end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to '/', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        flash[:errors]=@user.errors.messages
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    user_password=@user.encrypted_password;
    respond_to do |format|
      if @user.update(user_params)
        notice='User was successfully updated.'
        logout_user if user_password != @user.encrypted_password
        notice="User was successfully updated. You need to login again as you changed password" if user_password != @user.encrypted_password
        format.html { redirect_to '/', notice: notice }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%@event_session=@user%>
<%= form_for @user , :html => { :class => "form-horizontal event_session" ,'data-parsley-validate'=>''} do |f| %>
  <% if @event_session.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event_session.errors.count, "error") %> prohibited this event_session from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event_session.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


    <div class="form-group">
      <div class="col-lg-10">
        <%= f.label 'First Name', :class => 'control-label' %>
        <%= f.text_field :first_name, :class => 'form-control'%>
      </div>
    </div>

   <div class="form-group">
      <div class="col-lg-10">
        <%= f.label 'Last Name', :class => 'control-label' %>
        <%= f.text_field :last_name, :class => 'form-control'%>
      </div>
    </div>

  <div class="form-group">
      <div class="col-lg-10">
        <%= f.label 'Email', :class => 'control-label' %>
        <%= f.text_field :email, :class => 'form-control' ,'data-parsley-required'=>'','data-parsley-trigger'=>'change','data-parsley-type'=>"email"%>
      </div>
    </div>
  <div class="form-group">
      <div class="col-lg-10">
        <%= f.label 'Password', :class => 'control-label' %>
        <%= f.password_field :password, :class => 'form-control' ,'data-parsley-required'=>"#{@user.new_record?}",'data-parsley-trigger'=>'change','data-parsley-min-length'=>6%>
      </div>
    </div>
  <div class="actions">
    <%= f.submit 'Create' ,:class=>'btn btn-primary event-create'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="col-md-9 col-md-offset-2">
	<h1>Edit User</h1>
<%= render 'form' %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div class="col-md-6 col-md-offset-3" style="padding: 50px;">
	<h1>Sign In</h1>
<%= form_tag authorize_users_path , :html => { :class => "form-horizontal event_session" ,'data-parsley-validate'=>''} do |f| %>
  <div class="form-group">
        <%= label_tag 'Email','Email' ,:class => 'control-label' %>
        <%= text_field_tag :email,'', :class => 'form-control' ,'data-parsley-required'=>'','data-parsley-trigger'=>'change','data-parsley-type'=>"email"%>
    </div>
  <div class="form-group">
        <%= label_tag 'Password','Password', :class => 'control-label' %>
        <%= password_field_tag :password,'', :class => 'form-control' ,'data-parsley-required'=>'','data-parsley-trigger'=>'change'%>
    </div>
  <div class="actions">
    <%= submit_tag 'Login' ,:class=>'btn btn-primary event-create'%>
  </div>
  </div>
<% end %>


<div class="col-lg-1"></div>

app/views/users/new.html.erb
<div class="col-lg-1"></div>
<div class="col-lg-10">
	<h1>New User</h1>
<%= render 'form' %>
</div>
<div class="col-lg-1"></div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>