config/routes.rb
Rails.application.routes.draw do
  resources :users ,:only=>[:edit,:new,:create,:update] do 
   collection do
   get :login
   post :authorize
   get :logout
   end
  end
  resources :event_sessions
  resources :main ,:only=>[:index] do
    collection do
      post :login
      get :logout
    end
  end
  resources :questions ,:only=>[:index,:create] do
    member do
      get :vote_up
      post :remove
    end
    collection do
      get :refresh_questions
    end
  end

   root 'main#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HACK4T2" %></title>
    <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Avenir:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="<%=@body_class%>">
  <header class="light-purple-background">
  <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="logo" href="/">HACK4T2</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
   <ul class="nav navbar-nav navbar-right-custom">
          <%if is_login? && params[:controller] =~/questions/i && params[:action]=~/index/i%>
                <li><%= link_to "Leave Event", "/main/logout"  %></li>

          <%end%>

          <%unless current_user%>
           <li><%= link_to "Login", login_users_path  %></li>
           <%else%>
           <li><%=link_to "Edit Profile", edit_user_path(current_user['id'])%></li>
           <li><%= link_to "Manage Events", event_sessions_path  %></li>
           <li><%= link_to "Logout", logout_users_path  %></li>
          <%end%>
 </ul>
        </div>
    </div>
    </header>
    <div class="navbar navbar-default navbar-static-top ">
    <div class="main-container">
          <%= bootstrap_flash %>
          <%= yield %>
    </div> <!-- /container -->
        </div>
  <footer class="footer light-purple-background">
      <h4 class="text-center">Let’s hear it. Copyright The ArchiTech Platform 2015-16. All Rights Reserved.</h4>
  </footer>
  <script type="text/javascript">
  $(document).ready(function(){
  setTimeout(function(){
$('.alert.fade.in').fadeOut();
},5000);
  });
  </script>
  </body>
   

 
</html>